export enum LeadType {
  REACTION = 'REACTION',
  COMMENT = 'COMMENT',
  REPOST = 'REPOST',
  CONNECTION = 'CONNECTION',
  FOLLOWER = 'FOLLOWER',
  SEARCH_PERSON = 'SEARCH_PERSON',
  GROUP_MEMBERSHIP = 'GROUP_MEMBERSHIP',
  OTHER = 'OTHER',
}
